### ISSUE TITLE
Links to Team Websites Don't Work if Ommitting http://

### ISSUE THREAD

**Issue by neyre** [patfair/frclinks#10]
If a team didn't enter their website URL into TIMS with the http://, FRClinks doesn't cooperate.

If you go to a link like http://frclinks.com/w/968, it redirects to http://frclinks.frclinks.com/w/team968.com instead of http://team968.com.

**Comment by patfair** [comment]
This is actually because of a bug on FIRST's website -- the hyperlink on the Team 968 page points to http://www.firstinspires.org/team-event-search/team968.com. I can probably implement a hack to fix that, though.

**Comment by patfair** [comment]
Fixed in 0c0a2c6bee55ce7b118f23461ea0fc63ea5a3bba.
