### ISSUE TITLE
FIRST broke links again?

### ISSUE THREAD

**Issue by legoktm** [patfair/frclinks#9]
frclinks.com/t/604 -> http://www.firstinspires.org/whats-going-on/team/357405/ which is a 404 :(

**Comment by patfair** [comment]
Fixed team-related links in e14714fd3eb01712acf5579e1c4c47438c5ff2bc. I'll fix the others (docs, regionals, championship pages, etc.) as FIRST fixes them.

**Comment by legoktm** [comment]
Thank you!
